name: datasus_pe
version: "1.0.0"
config-version: 2

profile: datasus_pe

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  datasus_pe:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
